In [ ]:
import pandas as pd
from catboost import CatBoostClassifier, Pool
from itertools import product

In [ ]:
X_train = pd.read_parquet('data/X_train_half.parquet')
y_train = pd.read_parquet('data/y_train_half.parquet')
y_train = y_train['target']

In [ ]:
X_test = pd.read_parquet('data/X_test_half.parquet')
y_test = pd.read_parquet('data/y_test_half.parquet')
y_test = y_test['target']

In [ ]:
# Задаются категориальный признаки

cat_features = ['country', 'city', 'exp_group', 'os', 'source', 'topic', 'time_of_day']
cat_features_indices = [X_train.columns.get_loc(col) for col in cat_features]

In [ ]:
# Параметры грид серч заданы исходя из объема и сложности обучающего датасета

train_pool = Pool(X_train, y_train, cat_features=cat_features_indices)
test_pool = Pool(X_test, y_test, cat_features=cat_features_indices)

scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

grid = {
    'depth': [6, 8, 10],
    'learning_rate': [0.03, 0.05, 0.08],
    'l2_leaf_reg': [3, 5, 7]
}

keys = list(grid.keys())
all_params = list(product(*grid.values()))

results = []

for values in all_params:
    params = dict(zip(keys, values))

    model = CatBoostClassifier(
        **params,
        iterations=1000,
        loss_function='Logloss',
        eval_metric='AUC',
        scale_pos_weight=scale_pos_weight,
        grow_policy='SymmetricTree',    #Высокая скорость работы модели в проде
        task_type='GPU',
        verbose=100,
        od_type='Iter',
        od_wait=50,
        random_seed=10
    )

    model.fit(train_pool, eval_set=test_pool, plot=True)

    best_score = model.get_best_score()
    best_iter = model.get_best_iteration()

    row = params.copy()
    row['train_Logloss'] = best_score['learn']['Logloss']
    row['valid_Logloss'] = best_score['validation']['Logloss']
    row['valid_auc'] = best_score['validation']['AUC']
    row['best_iteration'] = best_iter
    row['gap'] = row['train_Logloss'] - row['valid_Logloss']
    results.append(row)

df_results = pd.DataFrame(results)
df_results = df_results.sort_values('valid_auc', ascending=False)

display(df_results.head(10))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6236913	best: 0.6236913 (0)	total: 275ms	remaining: 4m 34s
100:	test: 0.6455293	best: 0.6455424 (99)	total: 23.4s	remaining: 3m 28s
200:	test: 0.6565807	best: 0.6565807 (200)	total: 50.6s	remaining: 3m 20s
300:	test: 0.6604563	best: 0.6604563 (300)	total: 1m 16s	remaining: 2m 56s
400:	test: 0.6631187	best: 0.6631187 (400)	total: 1m 41s	remaining: 2m 31s
500:	test: 0.6653404	best: 0.6653404 (500)	total: 2m 6s	remaining: 2m 5s
600:	test: 0.6671707	best: 0.6671772 (599)	total: 2m 31s	remaining: 1m 40s
700:	test: 0.6686394	best: 0.6686394 (700)	total: 2m 55s	remaining: 1m 15s
800:	test: 0.6698587	best: 0.6698587 (800)	total: 3m 20s	remaining: 49.8s
900:	test: 0.6709129	best: 0.6709129 (900)	total: 3m 45s	remaining: 24.8s
999:	test: 0.6718152	best: 0.6718152 (999)	total: 4m 9s	remaining: 0us
bestTest = 0.6718152165
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6236913	best: 0.6236913 (0)	total: 255ms	remaining: 4m 14s
100:	test: 0.6455293	best: 0.6455424 (99)	total: 23.1s	remaining: 3m 25s
200:	test: 0.6565801	best: 0.6565801 (200)	total: 50.3s	remaining: 3m 19s
300:	test: 0.6604515	best: 0.6604515 (300)	total: 1m 15s	remaining: 2m 55s
400:	test: 0.6631323	best: 0.6631323 (400)	total: 1m 40s	remaining: 2m 29s
500:	test: 0.6653093	best: 0.6653093 (500)	total: 2m 5s	remaining: 2m 4s
600:	test: 0.6671075	best: 0.6671141 (599)	total: 2m 29s	remaining: 1m 39s
700:	test: 0.6686266	best: 0.6686266 (700)	total: 2m 54s	remaining: 1m 14s
800:	test: 0.6698026	best: 0.6698026 (800)	total: 3m 19s	remaining: 49.6s
900:	test: 0.6709039	best: 0.6709039 (900)	total: 3m 44s	remaining: 24.7s
999:	test: 0.6718232	best: 0.6718232 (999)	total: 4m 8s	remaining: 0us
bestTest = 0.6718232036
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6236913	best: 0.6236913 (0)	total: 213ms	remaining: 3m 33s
100:	test: 0.6458886	best: 0.6459034 (99)	total: 23s	remaining: 3m 24s
200:	test: 0.6566276	best: 0.6566276 (200)	total: 50.2s	remaining: 3m 19s
300:	test: 0.6604171	best: 0.6604171 (300)	total: 1m 15s	remaining: 2m 55s
400:	test: 0.6631148	best: 0.6631164 (399)	total: 1m 40s	remaining: 2m 30s
500:	test: 0.6653123	best: 0.6653123 (500)	total: 2m 5s	remaining: 2m 5s
600:	test: 0.6671932	best: 0.6671996 (599)	total: 2m 30s	remaining: 1m 39s
700:	test: 0.6686921	best: 0.6686921 (700)	total: 2m 54s	remaining: 1m 14s
800:	test: 0.6699309	best: 0.6699309 (800)	total: 3m 19s	remaining: 49.5s
900:	test: 0.6710013	best: 0.6710013 (900)	total: 3m 43s	remaining: 24.6s
999:	test: 0.6719255	best: 0.6719255 (999)	total: 4m 7s	remaining: 0us
bestTest = 0.6719254851
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6236913	best: 0.6236913 (0)	total: 215ms	remaining: 3m 35s
100:	test: 0.6546326	best: 0.6546326 (100)	total: 25.3s	remaining: 3m 45s
200:	test: 0.6616018	best: 0.6616057 (199)	total: 50.8s	remaining: 3m 21s
300:	test: 0.6650452	best: 0.6650452 (300)	total: 1m 15s	remaining: 2m 55s
400:	test: 0.6678060	best: 0.6678060 (400)	total: 1m 40s	remaining: 2m 29s
500:	test: 0.6698167	best: 0.6698167 (500)	total: 2m 4s	remaining: 2m 4s
600:	test: 0.6716109	best: 0.6716113 (599)	total: 2m 29s	remaining: 1m 38s
700:	test: 0.6729562	best: 0.6729562 (700)	total: 2m 53s	remaining: 1m 14s
800:	test: 0.6738570	best: 0.6738570 (800)	total: 3m 18s	remaining: 49.3s
900:	test: 0.6746804	best: 0.6746818 (899)	total: 3m 43s	remaining: 24.5s
999:	test: 0.6753813	best: 0.6753813 (999)	total: 4m 7s	remaining: 0us
bestTest = 0.6753813028
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6236913	best: 0.6236913 (0)	total: 209ms	remaining: 3m 28s
100:	test: 0.6544838	best: 0.6544838 (100)	total: 25.4s	remaining: 3m 45s
200:	test: 0.6616247	best: 0.6616251 (199)	total: 51.2s	remaining: 3m 23s
300:	test: 0.6653740	best: 0.6653740 (300)	total: 1m 15s	remaining: 2m 55s
400:	test: 0.6681567	best: 0.6681567 (400)	total: 1m 40s	remaining: 2m 30s
500:	test: 0.6700925	best: 0.6700925 (500)	total: 2m 5s	remaining: 2m 4s
600:	test: 0.6717277	best: 0.6717345 (599)	total: 2m 29s	remaining: 1m 39s
700:	test: 0.6730579	best: 0.6730579 (700)	total: 2m 54s	remaining: 1m 14s
800:	test: 0.6740435	best: 0.6740435 (800)	total: 3m 18s	remaining: 49.3s
900:	test: 0.6747586	best: 0.6747586 (900)	total: 3m 43s	remaining: 24.6s
999:	test: 0.6755265	best: 0.6755265 (999)	total: 4m 8s	remaining: 0us
bestTest = 0.6755264997
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6236913	best: 0.6236913 (0)	total: 221ms	remaining: 3m 40s
100:	test: 0.6544831	best: 0.6544831 (100)	total: 25.1s	remaining: 3m 43s
200:	test: 0.6616717	best: 0.6616762 (199)	total: 51.1s	remaining: 3m 22s
300:	test: 0.6652277	best: 0.6652357 (299)	total: 1m 15s	remaining: 2m 55s
400:	test: 0.6681291	best: 0.6681291 (400)	total: 1m 40s	remaining: 2m 29s
500:	test: 0.6701793	best: 0.6701793 (500)	total: 2m 4s	remaining: 2m 4s
600:	test: 0.6718249	best: 0.6718324 (599)	total: 2m 29s	remaining: 1m 39s
700:	test: 0.6731556	best: 0.6731556 (700)	total: 2m 54s	remaining: 1m 14s
800:	test: 0.6740367	best: 0.6740367 (800)	total: 3m 18s	remaining: 49.3s
900:	test: 0.6749797	best: 0.6749797 (900)	total: 3m 43s	remaining: 24.5s
999:	test: 0.6756533	best: 0.6756533 (999)	total: 4m 7s	remaining: 0us
bestTest = 0.6756532788
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6236913	best: 0.6236913 (0)	total: 209ms	remaining: 3m 29s
100:	test: 0.6592121	best: 0.6592256 (99)	total: 25.9s	remaining: 3m 50s
200:	test: 0.6656924	best: 0.6657080 (199)	total: 51.4s	remaining: 3m 24s
300:	test: 0.6697012	best: 0.6697012 (300)	total: 1m 15s	remaining: 2m 55s
400:	test: 0.6720930	best: 0.6720930 (400)	total: 1m 39s	remaining: 2m 28s
500:	test: 0.6737867	best: 0.6737867 (500)	total: 2m 4s	remaining: 2m 3s
600:	test: 0.6751873	best: 0.6751873 (600)	total: 2m 28s	remaining: 1m 38s
700:	test: 0.6762286	best: 0.6762286 (700)	total: 2m 53s	remaining: 1m 14s
800:	test: 0.6769958	best: 0.6770023 (798)	total: 3m 18s	remaining: 49.4s
900:	test: 0.6775086	best: 0.6775086 (900)	total: 3m 43s	remaining: 24.6s
999:	test: 0.6780155	best: 0.6780158 (990)	total: 4m 8s	remaining: 0us
bestTest = 0.6780157685
bestIteration = 990
Shrink model to first 991 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6236913	best: 0.6236913 (0)	total: 249ms	remaining: 4m 8s
100:	test: 0.6595400	best: 0.6595517 (98)	total: 25.6s	remaining: 3m 47s
200:	test: 0.6658240	best: 0.6658289 (199)	total: 50.8s	remaining: 3m 22s
300:	test: 0.6693251	best: 0.6693251 (300)	total: 1m 15s	remaining: 2m 55s
400:	test: 0.6717390	best: 0.6717390 (400)	total: 1m 39s	remaining: 2m 28s
500:	test: 0.6736936	best: 0.6736936 (500)	total: 2m 4s	remaining: 2m 3s
600:	test: 0.6747766	best: 0.6747881 (596)	total: 2m 29s	remaining: 1m 38s
700:	test: 0.6757145	best: 0.6757145 (700)	total: 2m 53s	remaining: 1m 14s
800:	test: 0.6765244	best: 0.6765244 (800)	total: 3m 18s	remaining: 49.4s
900:	test: 0.6771373	best: 0.6771393 (899)	total: 3m 43s	remaining: 24.6s
999:	test: 0.6776087	best: 0.6776119 (996)	total: 4m 8s	remaining: 0us
bestTest = 0.6776119471
bestIteration = 996
Shrink model to first 997 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6236913	best: 0.6236913 (0)	total: 249ms	remaining: 4m 9s
100:	test: 0.6591951	best: 0.6592255 (99)	total: 25.6s	remaining: 3m 47s
200:	test: 0.6654730	best: 0.6654730 (200)	total: 51s	remaining: 3m 22s
300:	test: 0.6693936	best: 0.6693936 (300)	total: 1m 15s	remaining: 2m 56s
400:	test: 0.6719542	best: 0.6719542 (400)	total: 1m 40s	remaining: 2m 30s
500:	test: 0.6736552	best: 0.6736552 (500)	total: 2m 5s	remaining: 2m 4s
600:	test: 0.6750286	best: 0.6750286 (600)	total: 2m 30s	remaining: 1m 39s
700:	test: 0.6759148	best: 0.6759148 (700)	total: 2m 55s	remaining: 1m 14s
800:	test: 0.6765219	best: 0.6765219 (800)	total: 3m 20s	remaining: 49.8s
900:	test: 0.6771879	best: 0.6771879 (900)	total: 3m 45s	remaining: 24.8s
999:	test: 0.6776831	best: 0.6776883 (996)	total: 4m 10s	remaining: 0us
bestTest = 0.6776883006
bestIteration = 996
Shrink model to first 997 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6249775	best: 0.6249775 (0)	total: 298ms	remaining: 4m 58s
100:	test: 0.6526222	best: 0.6526222 (100)	total: 33.2s	remaining: 4m 55s
200:	test: 0.6613045	best: 0.6613126 (199)	total: 1m 10s	remaining: 4m 39s
300:	test: 0.6660746	best: 0.6660746 (300)	total: 1m 46s	remaining: 4m 6s
400:	test: 0.6691929	best: 0.6691929 (400)	total: 2m 22s	remaining: 3m 32s
500:	test: 0.6718955	best: 0.6718955 (500)	total: 2m 58s	remaining: 2m 57s
600:	test: 0.6741753	best: 0.6741908 (599)	total: 3m 34s	remaining: 2m 22s
700:	test: 0.6758893	best: 0.6758893 (700)	total: 4m 11s	remaining: 1m 47s
800:	test: 0.6770616	best: 0.6770626 (799)	total: 4m 47s	remaining: 1m 11s
900:	test: 0.6779681	best: 0.6779808 (899)	total: 5m 24s	remaining: 35.7s
999:	test: 0.6787485	best: 0.6787485 (999)	total: 6m 1s	remaining: 0us
bestTest = 0.6787485182
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6249775	best: 0.6249775 (0)	total: 291ms	remaining: 4m 50s
100:	test: 0.6526205	best: 0.6526205 (100)	total: 33.3s	remaining: 4m 55s
200:	test: 0.6613049	best: 0.6613131 (199)	total: 1m 10s	remaining: 4m 39s
300:	test: 0.6660830	best: 0.6660830 (300)	total: 1m 46s	remaining: 4m 7s
400:	test: 0.6690990	best: 0.6690990 (400)	total: 2m 22s	remaining: 3m 33s
500:	test: 0.6718914	best: 0.6718914 (500)	total: 2m 59s	remaining: 2m 58s
600:	test: 0.6740438	best: 0.6740594 (599)	total: 3m 35s	remaining: 2m 22s
700:	test: 0.6758966	best: 0.6758966 (700)	total: 4m 12s	remaining: 1m 47s
800:	test: 0.6770421	best: 0.6770421 (800)	total: 4m 48s	remaining: 1m 11s
900:	test: 0.6780798	best: 0.6780929 (899)	total: 5m 25s	remaining: 35.8s
999:	test: 0.6788784	best: 0.6788784 (999)	total: 6m 2s	remaining: 0us
bestTest = 0.6788783669
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6249775	best: 0.6249775 (0)	total: 279ms	remaining: 4m 38s
100:	test: 0.6526189	best: 0.6526189 (100)	total: 33.4s	remaining: 4m 57s
200:	test: 0.6611538	best: 0.6611572 (199)	total: 1m 10s	remaining: 4m 40s
300:	test: 0.6658971	best: 0.6658971 (300)	total: 1m 46s	remaining: 4m 8s
400:	test: 0.6691256	best: 0.6691256 (400)	total: 2m 22s	remaining: 3m 33s
500:	test: 0.6719542	best: 0.6719542 (500)	total: 2m 59s	remaining: 2m 58s
600:	test: 0.6741861	best: 0.6742019 (599)	total: 3m 34s	remaining: 2m 22s
700:	test: 0.6759881	best: 0.6759881 (700)	total: 4m 11s	remaining: 1m 47s
800:	test: 0.6772147	best: 0.6772147 (800)	total: 4m 48s	remaining: 1m 11s
900:	test: 0.6781859	best: 0.6781859 (900)	total: 5m 24s	remaining: 35.7s
999:	test: 0.6788851	best: 0.6788851 (999)	total: 6m 1s	remaining: 0us
bestTest = 0.6788851023
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6249775	best: 0.6249775 (0)	total: 283ms	remaining: 4m 42s
100:	test: 0.6595434	best: 0.6595739 (99)	total: 35.2s	remaining: 5m 13s
200:	test: 0.6672528	best: 0.6672683 (199)	total: 1m 10s	remaining: 4m 41s
300:	test: 0.6718534	best: 0.6718534 (300)	total: 1m 47s	remaining: 4m 8s
400:	test: 0.6749349	best: 0.6749349 (400)	total: 2m 23s	remaining: 3m 35s
500:	test: 0.6771842	best: 0.6771873 (498)	total: 3m	remaining: 2m 59s
600:	test: 0.6786451	best: 0.6786499 (599)	total: 3m 36s	remaining: 2m 24s
700:	test: 0.6794994	best: 0.6794994 (700)	total: 4m 14s	remaining: 1m 48s
800:	test: 0.6800998	best: 0.6801065 (798)	total: 4m 51s	remaining: 1m 12s
900:	test: 0.6806689	best: 0.6806689 (900)	total: 5m 29s	remaining: 36.2s
999:	test: 0.6809634	best: 0.6809734 (996)	total: 6m 6s	remaining: 0us
bestTest = 0.680973351
bestIteration = 996
Shrink model to first 997 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6249775	best: 0.6249775 (0)	total: 295ms	remaining: 4m 54s
100:	test: 0.6595464	best: 0.6595781 (99)	total: 34.6s	remaining: 5m 8s
200:	test: 0.6672364	best: 0.6672364 (200)	total: 1m 10s	remaining: 4m 41s
300:	test: 0.6717945	best: 0.6717945 (300)	total: 1m 46s	remaining: 4m 8s
400:	test: 0.6750791	best: 0.6750791 (400)	total: 2m 22s	remaining: 3m 33s
500:	test: 0.6771792	best: 0.6771792 (500)	total: 2m 59s	remaining: 2m 59s
600:	test: 0.6786645	best: 0.6786645 (600)	total: 3m 36s	remaining: 2m 23s
700:	test: 0.6795634	best: 0.6795634 (700)	total: 4m 13s	remaining: 1m 48s
800:	test: 0.6801763	best: 0.6801763 (800)	total: 4m 50s	remaining: 1m 12s
900:	test: 0.6806580	best: 0.6806580 (900)	total: 5m 28s	remaining: 36.1s
999:	test: 0.6808809	best: 0.6808809 (999)	total: 6m 5s	remaining: 0us
bestTest = 0.6808809042
bestIteration = 999

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6249775	best: 0.6249775 (0)	total: 286ms	remaining: 4m 45s
100:	test: 0.6591716	best: 0.6591716 (100)	total: 34.5s	remaining: 5m 7s
200:	test: 0.6672072	best: 0.6672145 (199)	total: 1m 10s	remaining: 4m 41s
300:	test: 0.6719760	best: 0.6719760 (300)	total: 1m 46s	remaining: 4m 7s
400:	test: 0.6751966	best: 0.6751966 (400)	total: 2m 22s	remaining: 3m 33s
500:	test: 0.6774040	best: 0.6774040 (500)	total: 2m 59s	remaining: 2m 58s
600:	test: 0.6787729	best: 0.6787743 (598)	total: 3m 35s	remaining: 2m 23s
700:	test: 0.6797422	best: 0.6797422 (700)	total: 4m 13s	remaining: 1m 47s
800:	test: 0.6803530	best: 0.6803565 (799)	total: 4m 50s	remaining: 1m 12s
900:	test: 0.6808016	best: 0.6808025 (899)	total: 5m 28s	remaining: 36.1s
999:	test: 0.6810912	best: 0.6810979 (998)	total: 6m 6s	remaining: 0us
bestTest = 0.6810978949
bestIteration = 998
Shrink model to first 999 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6249775	best: 0.6249775 (0)	total: 334ms	remaining: 5m 33s
100:	test: 0.6645968	best: 0.6645968 (100)	total: 35.7s	remaining: 5m 17s
200:	test: 0.6727952	best: 0.6728131 (199)	total: 1m 12s	remaining: 4m 46s
300:	test: 0.6768734	best: 0.6768734 (300)	total: 1m 48s	remaining: 4m 10s
400:	test: 0.6786664	best: 0.6786664 (400)	total: 2m 24s	remaining: 3m 35s
500:	test: 0.6798708	best: 0.6798708 (500)	total: 3m 1s	remaining: 3m
600:	test: 0.6806477	best: 0.6806498 (597)	total: 3m 37s	remaining: 2m 24s
700:	test: 0.6812115	best: 0.6812212 (697)	total: 4m 15s	remaining: 1m 49s
800:	test: 0.6815144	best: 0.6815144 (800)	total: 4m 53s	remaining: 1m 12s
900:	test: 0.6816936	best: 0.6816936 (900)	total: 5m 31s	remaining: 36.4s
999:	test: 0.6819000	best: 0.6819359 (973)	total: 6m 9s	remaining: 0us
bestTest = 0.6819359362
bestIteration = 973
Shrink model to first 974 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6249775	best: 0.6249775 (0)	total: 279ms	remaining: 4m 38s
100:	test: 0.6646520	best: 0.6646520 (100)	total: 35.7s	remaining: 5m 17s
200:	test: 0.6728061	best: 0.6728214 (199)	total: 1m 11s	remaining: 4m 46s
300:	test: 0.6768262	best: 0.6768262 (300)	total: 1m 48s	remaining: 4m 11s
400:	test: 0.6788481	best: 0.6788481 (400)	total: 2m 24s	remaining: 3m 35s
500:	test: 0.6800377	best: 0.6800377 (500)	total: 3m 1s	remaining: 3m 1s
600:	test: 0.6808820	best: 0.6808821 (596)	total: 3m 38s	remaining: 2m 25s
700:	test: 0.6812217	best: 0.6812217 (700)	total: 4m 16s	remaining: 1m 49s
800:	test: 0.6815619	best: 0.6815619 (800)	total: 4m 55s	remaining: 1m 13s
900:	test: 0.6817780	best: 0.6817844 (899)	total: 5m 34s	remaining: 36.7s
bestTest = 0.6817843914
bestIteration = 899
Shrink model to first 900 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6249775	best: 0.6249775 (0)	total: 283ms	remaining: 4m 42s
100:	test: 0.6646532	best: 0.6646532 (100)	total: 35.8s	remaining: 5m 18s
200:	test: 0.6727620	best: 0.6727787 (199)	total: 1m 11s	remaining: 4m 44s
300:	test: 0.6770015	best: 0.6770015 (300)	total: 1m 47s	remaining: 4m 10s
400:	test: 0.6787865	best: 0.6787865 (400)	total: 2m 24s	remaining: 3m 35s
500:	test: 0.6801457	best: 0.6801457 (500)	total: 3m 1s	remaining: 3m
600:	test: 0.6809664	best: 0.6809664 (600)	total: 3m 39s	remaining: 2m 25s
700:	test: 0.6812856	best: 0.6812871 (699)	total: 4m 16s	remaining: 1m 49s
800:	test: 0.6815870	best: 0.6815909 (799)	total: 4m 55s	remaining: 1m 13s
900:	test: 0.6818181	best: 0.6818181 (900)	total: 5m 33s	remaining: 36.7s
bestTest = 0.6818514466
bestIteration = 916
Shrink model to first 917 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6263884	best: 0.6263884 (0)	total: 375ms	remaining: 6m 14s
100:	test: 0.6568323	best: 0.6568494 (99)	total: 46.9s	remaining: 6m 57s
200:	test: 0.6671508	best: 0.6671641 (199)	total: 1m 39s	remaining: 6m 35s
300:	test: 0.6725949	best: 0.6726015 (299)	total: 2m 31s	remaining: 5m 52s
400:	test: 0.6756472	best: 0.6756472 (400)	total: 3m 24s	remaining: 5m 5s
500:	test: 0.6780508	best: 0.6780508 (500)	total: 4m 17s	remaining: 4m 16s
600:	test: 0.6801382	best: 0.6801428 (599)	total: 5m 11s	remaining: 3m 27s
700:	test: 0.6810687	best: 0.6810687 (700)	total: 6m 6s	remaining: 2m 36s
800:	test: 0.6815680	best: 0.6815680 (800)	total: 7m	remaining: 1m 44s
900:	test: 0.6818990	best: 0.6819016 (899)	total: 7m 56s	remaining: 52.4s
999:	test: 0.6821176	best: 0.6821228 (996)	total: 8m 50s	remaining: 0us
bestTest = 0.682122767
bestIteration = 996
Shrink model to first 997 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6263887	best: 0.6263887 (0)	total: 374ms	remaining: 6m 13s
100:	test: 0.6570134	best: 0.6570134 (100)	total: 46.9s	remaining: 6m 57s
200:	test: 0.6672850	best: 0.6672940 (199)	total: 1m 39s	remaining: 6m 36s
300:	test: 0.6729271	best: 0.6729271 (300)	total: 2m 31s	remaining: 5m 52s
400:	test: 0.6759515	best: 0.6759515 (400)	total: 3m 23s	remaining: 5m 4s
500:	test: 0.6783180	best: 0.6783180 (500)	total: 4m 16s	remaining: 4m 15s
600:	test: 0.6803132	best: 0.6803132 (600)	total: 5m 11s	remaining: 3m 26s
700:	test: 0.6811918	best: 0.6811918 (700)	total: 6m 5s	remaining: 2m 36s
800:	test: 0.6816633	best: 0.6816787 (795)	total: 6m 59s	remaining: 1m 44s
900:	test: 0.6819346	best: 0.6819348 (899)	total: 7m 56s	remaining: 52.3s
999:	test: 0.6821513	best: 0.6821665 (994)	total: 8m 50s	remaining: 0us
bestTest = 0.6821664572
bestIteration = 994
Shrink model to first 995 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6263885	best: 0.6263885 (0)	total: 372ms	remaining: 6m 11s
100:	test: 0.6567189	best: 0.6567189 (100)	total: 47s	remaining: 6m 58s
200:	test: 0.6669627	best: 0.6669788 (199)	total: 1m 39s	remaining: 6m 35s
300:	test: 0.6727775	best: 0.6727775 (300)	total: 2m 32s	remaining: 5m 53s
400:	test: 0.6756068	best: 0.6756068 (400)	total: 3m 23s	remaining: 5m 3s
500:	test: 0.6779509	best: 0.6779509 (500)	total: 4m 16s	remaining: 4m 15s
600:	test: 0.6799883	best: 0.6799976 (597)	total: 5m 11s	remaining: 3m 26s
700:	test: 0.6809713	best: 0.6809713 (700)	total: 6m 5s	remaining: 2m 36s
800:	test: 0.6815362	best: 0.6815436 (795)	total: 7m	remaining: 1m 44s
900:	test: 0.6819592	best: 0.6819592 (900)	total: 7m 56s	remaining: 52.4s
bestTest = 0.681971252
bestIteration = 903
Shrink model to first 904 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6263884	best: 0.6263884 (0)	total: 378ms	remaining: 6m 17s
100:	test: 0.6637284	best: 0.6637562 (99)	total: 49.6s	remaining: 7m 21s
200:	test: 0.6734360	best: 0.6734388 (199)	total: 1m 40s	remaining: 6m 41s
300:	test: 0.6776302	best: 0.6776404 (299)	total: 2m 33s	remaining: 5m 55s
400:	test: 0.6802344	best: 0.6802447 (397)	total: 3m 28s	remaining: 5m 11s
500:	test: 0.6810374	best: 0.6810575 (488)	total: 4m 22s	remaining: 4m 21s
600:	test: 0.6815937	best: 0.6816195 (592)	total: 5m 17s	remaining: 3m 30s
bestTest = 0.6816722155
bestIteration = 649
Shrink model to first 650 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6263887	best: 0.6263887 (0)	total: 375ms	remaining: 6m 15s
100:	test: 0.6643633	best: 0.6643869 (99)	total: 49.5s	remaining: 7m 21s
200:	test: 0.6735022	best: 0.6735241 (199)	total: 1m 41s	remaining: 6m 44s
300:	test: 0.6778365	best: 0.6778365 (300)	total: 2m 33s	remaining: 5m 57s
400:	test: 0.6801551	best: 0.6801594 (399)	total: 3m 27s	remaining: 5m 10s
500:	test: 0.6809908	best: 0.6809977 (498)	total: 4m 22s	remaining: 4m 21s
600:	test: 0.6813160	best: 0.6813266 (595)	total: 5m 16s	remaining: 3m 30s
700:	test: 0.6817234	best: 0.6817234 (700)	total: 6m 12s	remaining: 2m 38s
800:	test: 0.6818694	best: 0.6818791 (774)	total: 7m 7s	remaining: 1m 46s
bestTest = 0.6818791032
bestIteration = 774
Shrink model to first 775 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6263885	best: 0.6263885 (0)	total: 378ms	remaining: 6m 17s
100:	test: 0.6643713	best: 0.6643931 (99)	total: 49.7s	remaining: 7m 21s
200:	test: 0.6737534	best: 0.6737696 (199)	total: 1m 42s	remaining: 6m 45s
300:	test: 0.6775965	best: 0.6776057 (299)	total: 2m 33s	remaining: 5m 57s
400:	test: 0.6802044	best: 0.6802067 (399)	total: 3m 27s	remaining: 5m 10s
500:	test: 0.6810800	best: 0.6811007 (488)	total: 4m 22s	remaining: 4m 21s
600:	test: 0.6817011	best: 0.6817031 (599)	total: 5m 17s	remaining: 3m 31s
700:	test: 0.6819614	best: 0.6820035 (684)	total: 6m 13s	remaining: 2m 39s
bestTest = 0.6820034683
bestIteration = 684
Shrink model to first 685 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6263884	best: 0.6263884 (0)	total: 384ms	remaining: 6m 24s
100:	test: 0.6706508	best: 0.6706508 (100)	total: 50.8s	remaining: 7m 32s
200:	test: 0.6781657	best: 0.6781657 (200)	total: 1m 43s	remaining: 6m 50s
300:	test: 0.6801949	best: 0.6801976 (298)	total: 2m 36s	remaining: 6m 4s
400:	test: 0.6806812	best: 0.6807044 (397)	total: 3m 32s	remaining: 5m 16s
bestTest = 0.6808630228
bestIteration = 433
Shrink model to first 434 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6263887	best: 0.6263887 (0)	total: 383ms	remaining: 6m 22s
100:	test: 0.6701565	best: 0.6702015 (99)	total: 51.6s	remaining: 7m 39s
200:	test: 0.6784230	best: 0.6784619 (199)	total: 1m 43s	remaining: 6m 52s
300:	test: 0.6804481	best: 0.6804692 (299)	total: 2m 37s	remaining: 6m 6s
400:	test: 0.6807965	best: 0.6808940 (376)	total: 3m 33s	remaining: 5m 18s
bestTest = 0.6808939576
bestIteration = 376
Shrink model to first 377 iterations.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6263885	best: 0.6263885 (0)	total: 376ms	remaining: 6m 15s
100:	test: 0.6705826	best: 0.6705826 (100)	total: 50.9s	remaining: 7m 33s
200:	test: 0.6782973	best: 0.6783130 (199)	total: 1m 44s	remaining: 6m 53s
300:	test: 0.6808629	best: 0.6808629 (300)	total: 2m 38s	remaining: 6m 8s
400:	test: 0.6811005	best: 0.6811986 (368)	total: 3m 33s	remaining: 5m 19s
bestTest = 0.681198597
bestIteration = 368
Shrink model to first 369 iterations.

,depth,learning_rate,l2_leaf_reg,train_Logloss,valid_Logloss,valid_auc,best_iteration,gap
19,10,0.03,5,0.611423,0.635153,0.682166,994,-0.023730
18,10,0.03,3,0.610954,0.635223,0.682123,996,-0.024269
23,10,0.05,7,0.606268,0.635119,0.682003,684,-0.028851
20,10,0.03,7,0.612831,0.635291,0.681971,903,-0.022460
15,8,0.08,3,0.614855,0.635582,0.681936,973,-0.020727
22,10,0.05,5,0.602147,0.635122,0.681879,774,-0.032975
17,8,0.08,7,0.615915,0.635479,0.681851,916,-0.019563
16,8,0.08,5,0.616090,0.635586,0.681784,899,-0.019496
21,10,0.05,3,0.606442,0.635351,0.681672,649,-0.028909
26,10,0.08,7,0.609206,0.635598,0.681199,368,-0.026392

In [ ]:
df_results

,depth,learning_rate,l2_leaf_reg,train_Logloss,valid_Logloss,valid_auc,best_iteration,gap
19,10,0.03,5,0.611423,0.635153,0.682166,994,-0.023730
18,10,0.03,3,0.610954,0.635223,0.682123,996,-0.024269
23,10,0.05,7,0.606268,0.635119,0.682003,684,-0.028851
20,10,0.03,7,0.612831,0.635291,0.681971,903,-0.022460
15,8,0.08,3,0.614855,0.635582,0.681936,973,-0.020727
22,10,0.05,5,0.602147,0.635122,0.681879,774,-0.032975
17,8,0.08,7,0.615915,0.635479,0.681851,916,-0.019563
16,8,0.08,5,0.616090,0.635586,0.681784,899,-0.019496
21,10,0.05,3,0.606442,0.635351,0.681672,649,-0.028909
26,10,0.08,7,0.609206,0.635598,0.681199,368,-0.026392
14,8,0.05,7,0.623013,0.636382,0.681098,998,-0.013369
12,8,0.05,3,0.622649,0.636415,0.680973,996,-0.013766
25,10,0.08,5,0.608080,0.635788,0.680894,376,-0.027708
13,8,0.05,5,0.622840,0.636424,0.680881,999,-0.013584
24,10,0.08,3,0.603367,0.635689,0.680863,433,-0.032322
11,8,0.03,7,0.629901,0.638194,0.678885,999,-0.008294
10,8,0.03,5,0.629874,0.638171,0.678878,999,-0.008297
9,8,0.03,3,0.629771,0.638260,0.678749,999,-0.008489
6,6,0.08,3,0.630582,0.638733,0.678016,990,-0.008151
8,6,0.08,7,0.630768,0.638992,0.677688,996,-0.008224
7,6,0.08,5,0.630843,0.639005,0.677612,996,-0.008162
5,6,0.05,7,0.635076,0.640462,0.675653,999,-0.005385
4,6,0.05,5,0.635098,0.640494,0.675526,999,-0.005396
3,6,0.05,3,0.635075,0.640571,0.675381,999,-0.005496
2,6,0.03,7,0.639428,0.642822,0.671925,999,-0.003394
1,6,0.03,5,0.639469,0.642904,0.671823,999,-0.003435
0,6,0.03,3,0.639477,0.642895,0.671815,999,-0.003418

## Выводы
Выбрана одна модель для дальнейщего обучения:
№ 14 (8, 0.05 и 7) Т.к. у неё valid_auc близок к максимальной, но низкий gap. Т.е. данная модель обладает хорошей обобщающей способностью